name: whisper-dev

services:
  
  whisper-valkey:
    image: valkey/valkey:alpine
    container_name: whisper-valkey-dev
    # restart: always
    command: /bin/sh -c "redis-server --requirepass ${VALKEY_PASSWORD} --save 60 1 --loglevel warning"
    volumes:
      - valkey_data:/data

volumes:
  valkey_data: