name: whisper-server

services:

  whisper-server:
    container_name: whisper-server
    env_file: .env.prod
    build:
      context: .
    network_mode: bridge
    restart: always
    ports:
       - "127.0.0.1:8080:8080"
    volumes:
       - /etc/localtime:/etc/localtime:ro
    environment:
      - GIN_MODE=${GIN_MODE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=whisper-postgres
      - POSTGRES_DB=${POSTGRES_DB}
      - VALKEY_HOST=whisper-valkey
      - VALKEY_PASSWORD=${VALKEY_PASSWORD}
      - ADMIN_MAIL=${ADMIN_MAIL}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
  
  whisper-postgres:
    image: postgres:alpine
    container_name: whisper-postgres
    env_file: .env.prod
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
  
  whisper-valkey:
    image: valkey/valkey:latest
    container_name: whisper-valkey
    env_file: .env.prod
    restart: always
    command: /bin/sh -c "redis-server --requirepass ${VALKEY_PASSWORD} --save 60 1 --loglevel warning"
    volumes:
      - valkey_data:/data

volumes:
  postgres_data:
  valkey_data: